version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: "b2blisting"
      POSTGRES_USER: "b2b"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"